### PR TITLE
fix: truncate user information if it is too long

### LINKED ISSUE #6769: Cant open profile. Error [object Object]
## 💡 Summary

When i try to open profile https://gentoo.live/sathariel i have error [object Object]

levels.error

`[api] Internal error occurred in ap/show: invalid json response body at https://gentoo.live/sathariel reason: Unexpected token < in JSON at position 0`

levels.warning

`[api] failed to resolve remote user: Error: invalid person: invalid name`

Nickname - :unicursalpink: Sathy de los Muertos 3: La venganza :chaos_pink:

## 🙂 Expected Behavior

Profile opened.

## ☹️ Actual Behavior

When i search @sathariel@gentoo.live

When i search https://gentoo.live/sathariel

## 📝 Steps to Reproduce

1. Click Search button.
2. Paste https://gentoo.live/sathariel or @sathariel@gentoo.live

## 📌 Environment

Debian GNU/Linux 10 (buster) x86_64
Misskey v12.50.0
Node.js v14.13.1
PostgreSQL v13.0 (Debian 13.0-1.pgdg100+1)
Redis v5.0.3

### PR DESCRIPTION
**Pull request by Johann150**
# What
Some AP software allows for user names or summaries to be very long.
Misskey can not handle this and the profile page can not be opened and
no activities from such users can be seen.

Instead, the user name and summary are cut off after the maximum length.
so misskey can still process the activities of the profile.

fixes #6769 

# Why
Without this, the profiles and the user notes, reactions can not be federated.

Instead of failing completely, this allows to federate other information.

# Additional info (optional)
This can remove some information from the user summary, but Misskey already shows a warning for profiles from remote instances. 

This is also [part of `misskey-extra`](https://github.com/JakeMBauer/Misskey-Extras/blob/main/patches/README.md#Truncate-Profiles), and is already used on some instances.

### CODE REVIEW

**Comment by Johann150** [comment]
also solves #7627

File: src/remote/activitypub/models/person.ts [hunk 1]
```diff
@@ -31,6 +31,9 @@ import { normalizeForSearch } from '@/misc/normalize-for-search';
 
 const logger = apLogger;
 
+const nameLength = 128;
+const summaryLength = 2048;
```
Comment (Johann150) [inline src/remote/activitypub/models/person.ts:35]: maybe these should be stored in `misskey/src/misc/hard-limits.ts` ?

Comment (syuilo) [reply src/remote/activitypub/models/person.ts:35]: I will to do so!

**Comment by syuilo** [comment]
🙏

**Comment by mei23** [comment]
Because the DB column is unextended.
https://github.com/misskey-dev/misskey/blob/b5cadeca2e02f88d46625f27c3fcc796e45c2526/src/models/entities/user-profile.ts#L32-L36

Not only must it pass validate, but it must also be truncate when inserting/updating.
https://github.com/misskey-dev/misskey/blob/b5cadeca2e02f88d46625f27c3fcc796e45c2526/src/remote/activitypub/models/person.ts#L173
