### PR TITLE
fix(backend): 連合モードが「なし」の場合はactivity jsonへのリンクタグを省略するように

### LINKED ISSUE #15975: 連合なしサーバーでも `link[rel="alternate"][type="application/json+activity"]` が付与されている
### 💡 Summary

連合なしサーバーでも `link[rel="alternate"][type="application/json+activity"]` が付与されている。

`application/json+activity`での配送は行っていないため、付与するべきではない

keywords: no federation link alternate activity

### 🥰 Expected Behavior

`link[rel="alternate"][type="application/json+activity"]` タグが連合無効だと付与されない

### 🤬 Actual Behavior

`link[rel="alternate"][type="application/json+activity"]` タグが連合無効でも付与される

### 📝 Steps to Reproduce

連合なしサーバーのレスポンスを確認する

テストでは`curl 'https://xissmie.xfolio.jp/notes/a7gygy1ovsquyqnl'`を行いました

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):　N/A
* Browser: Curl
* Server URL: https://xissmie.xfolio.jp/
* Misskey: 2025.2.1
```

### 🛰 Backend Environment (for server admin)

```markdown
N/A
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

### PR DESCRIPTION
**Pull request by kakkokari-gtyih**
## Why

Fix #15975

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

File: packages/backend/src/server/web/ClientServerService.ts [hunk 1]
```diff
@@ -212,6 +212,7 @@ export class ClientServerService {
 			instanceUrl: this.config.url,
 			metaJson: htmlSafeJsonStringify(await this.metaEntityService.packDetailed(meta)),
 			now: Date.now(),
+			federationDisabled: this.meta.federation === 'none',
```
Comment (syuilo) [inline packages/backend/src/server/web/ClientServerService.ts]: federationEnabledにした方が否定演算子使わずに済んで読みやすそう

Comment (kakkokari-gtyih) [reply packages/backend/src/server/web/ClientServerService.ts]: done

**Comment by syuilo** [comment]
🙏
