### PR TITLE
fix: add id for activitypub follows

### LINKED ISSUE #8218: Follow Activityに対してstringでAccept/Rejectを受け取った場合に詰んでしまう
## 💡 Summary

Misskey sends
```yml
  id: https://local/:uuid ★random id
  type: Follow
  actor: https://local/users/follower
  object: https://remote/users/followee
```

Misskey receives... This is OK 
```yml
  type: Accept
  actor: https://remote/users/followee
  object:
    id: https://local/:uuid ★random id
    type: Follow
    actor: https://local/users/follower
    object: https://remote/users/followee
```

Suppose you receive this, This is valid. But unable to perform processing.
```yml
  type: Accept
  actor: https://remote/users/followee
  object: https://local/:uuid ★random id
```

#8165

## 📝 Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by Johann150**
# What
`Follow` activities are rendered with a proper `id` so that when servers only respond with an accept with the id, it can be processed correctly.

The respective activity is provided at the new URL.
# Why
fix #8218

# Additional Info
together with #8635 this allows to follow users on Owncast 0.0.11 correctly (#8165)

### CODE REVIEW

**Comment by mei23** [comment]
> together with https://github.com/misskey-dev/misskey/pull/8635 this allows to follow users on Owncast 0.0.11 correctly (https://github.com/misskey-dev/misskey/issues/8165)

Need a parser for `https://example.com/follows/<follower id>/<followee id>` ?

**Comment by Johann150** [comment]
I'm not sure where you mean this parser should be added? Misskey resolves everything via HTTP at the moment as far as I know (#8688), so that is also what I did for now: https://github.com/misskey-dev/misskey/pull/8689/files#diff-f6e4f1a116f4168da1998803a9ddb39d8f8a395aeced91cf67c4e42519807996R229

**Comment by mei23** [comment]
I think need to interpret the Accept payload returned remotely.
https://github.com/misskey-dev/misskey/blob/fee2878b98253f2510ae2bc5c746c058a043ef82/packages/backend/src/remote/activitypub/kernel/accept/follow.ts

#8688
`Resolver.resolve()` only gets the JSON of the AP, not the information required for local DB processing.

**Comment by Johann150** [comment]
The `Accept` payload will be turned into the AP object by this `Resolver.resolve`:
https://github.com/misskey-dev/misskey/blob/fee2878b98253f2510ae2bc5c746c058a043ef82/packages/backend/src/remote/activitypub/kernel/accept/index.ts#L16-L19
This will then fetch the AP JSON from the new route I added. Just as before, the AP JSON representation should contain all the necessary information. I'm not sure which information is missing.

**Comment by mei23** [comment]
Ah, it may work. But not expecting to get a remote object via http.
I haven't seen it well, but maybe validation is needed.

**Comment by Johann150** [comment]
Yes, I thought about validation, see my (edited) post in the original issue: https://github.com/misskey-dev/misskey/issues/8218#issuecomment-1127710881
> I first thought this could be a security vulnerability because remote ActivityPub servers could send crafted messages with these IDs, but since Misskey checks that a follow request exists when accepting, it should be fine.
> https://github.com/misskey-dev/misskey/blob/fee2878b98253f2510ae2bc5c746c058a043ef82/packages/backend/src/services/following/requests/accept.ts#L12-L19

**Comment by mei23** [comment]
Okay, I was worried about Undo and Reject processing, but maybe it's okay.

File: packages/backend/src/server/activitypub.ts [hunk 1]
```diff
@@ -224,4 +225,24 @@ router.get('/likes/:like', async ctx => {
...
+
+	if (follower == null || followee == null) {
+		ctx.status = 404;
+		return;
+	}
+
+	ctx.body = renderActivity(renderFollow(follower, followee));
+	ctx.set('Cache-Control', 'public, max-age=180');
+	setResponseType(ctx);
+});
```
Comment (mei23) [inline packages/backend/src/server/activitypub.ts]: うーん、インスタンスに保存されているユーザーのパターンなら、どんなパターンでも作らされてしまうのが少し気になってる。

Comment (Johann150) [reply packages/backend/src/server/activitypub.ts]: Yes, it will be technically possible to create any pair of users stored in the database.

As I have said above already, being able to create this means little: Misskey uses follow requests to track whether a follow was requested by a local user. Before accepting a follow, Misskey checks that a matching follow request exists. If it does not exist, nothing happens.

Similarly, using this ID to create a fraudulent Activity should also not work because the actor that made the signature will not be the same as the `actor` of the `Follow` activity. This would only be a concern if the private key becomes public, which is in my understanding outside the threat model of Misskey.

To ensure this is not abused I think it does make sense to check that the follower is a local user and the followee is not a local user by adding those parameters to the queries.

If this is not what you meant, please be more specific.

Comment (mei23) [reply packages/backend/src/server/activitypub.ts]: まあ、そうは思うわ…

でもやっぱり、HTTP Resolver経由で取得するのが引っかかる。（endpointの公開が必要になってしまう）
Activity endpointは公開せずに /packages/backend/src/remote/activitypub/kernel/accept/follow.ts などでURLパースでDB解決するとかしたい。
Related #8688

Comment (Johann150) [reply packages/backend/src/server/activitypub.ts]: The resolve of the accepted object happens in `packages/backend/src/remote/activitypub/kernel/accept/index.ts`, and there a `Resolver` is used. Parsing the URL instead of making a HTTP request is the job of `DbResolver`. I am not sure if I can replace `Resolver` with a `DbResolver` there without breaking behaviour.

If it is possible, a new `getFollowFromApId` function could be added to `DbResolver` to be used instead, since misskey only seems to be able to accept `Follow` objects there anyway.

Comment (mei23) [reply packages/backend/src/server/activitypub.ts]: I was just thinking about it.

In the case of Undo, there can be Follow and Block, but since it is from local, it can be identified by URL Path.

**Comment by mei23** [comment]
It may be another issue, but should the path that stores Activity of ActivityPub be isolated to /activities/ or another path?

**Comment by mei23** [comment]
There is a possibility of conflict when implementing the Web or other protocols, and in other implementations we often see isolation in a dedicated path.

**Comment by Johann150** [comment]
It might have been a good design idea if it had been made at an earlier point. I think even besides it being a separate issue, such a change has the potential to (badly) break federation for servers that keep track of the existing IDs (for example: Misskey keeps track of the remote IDs of notes).

So in Misskey's case I think it is too late to change this.

**Comment by mei23** [comment]
Yes, most objects are too slow, but I'm wondering what about new Activities.

File: packages/backend/src/server/activitypub.ts (hunk 1 above)
Comment (Johann150) [reply packages/backend/src/server/activitypub.ts]: As I said before, I think this should be handled in the issue you linked, because in my opinion, there needs to be a way to automatically fetching the right type of object locally, as I wrote in <https://github.com/misskey-dev/misskey/issues/8688#issuecomment-1128811932>.
An additional complexity is that the kernel always uses ActivityPub objects, so use of `DbResolver` might be inappropriate because it returns database objects.

**Comment by Johann150** [comment]
Having different URL styles would require changes to `DbResolver.parseUri` which might be used in the future e.g. for #8688. So I do not want to create a mess of different URL formats.

**Comment by mei23** [comment]
Okay, there is such an idea.

However, `DbResolver.parseUri` does not assume two arguments, so it may be necessary to change it after all ...

**Comment by Johann150** [comment]
It would still create a mess of different URLs which is not something I would want to introduce.

**Comment by mei23** [comment]
How about `blocks`? I think it's the same pattern as `follows`.

**Comment by mei23** [comment]
> How about `blocks`? I think it's the same pattern as `follows`.

But unlike `follows`, ` blocks` can use an immutable DB ID.

**Comment by Johann150** [comment]
Does it matter for blocks? I don't think there is any case where local blocks are handled via ActivityPub, since they do not have to be `Accept`ed.

But I guess it would be best practice anyway...

**Comment by mei23** [comment]
I agree. There is no problem for the time b

**Comment by syuilo** [comment]
👍
