### PR TITLE
fix(frontend): modalが正しく閉じられていないのを修正

### LINKED ISSUE #14304: 「通報の通知先を追加」ダイアログを開いて閉じると操作を受け付けなくなる
### 💡 Summary

「コントロールパネル」→「通報」→「通知設定」→「通報の連絡先を追加」を押してダイアログを開き、（追加してもしなくても）「OK」または「キャンセル」または右上閉じるボタンで閉じるとリロードするまで画面が一切操作できなくなってしまう。

### 🥰 Expected Behavior

「通報の連絡先を追加」ダイアログを閉じたあと画面が操作できる。

### 🤬 Actual Behavior

「通報の連絡先を追加」ダイアログを閉じたあとリロードするまで画面が操作できない（マウスクリックが作用しない）

### 📝 Steps to Reproduce

1. 「コントロールパネル」→「通報」→「通知設定」→「通報の連絡先を追加」を押してダイアログを開く
2. ダイアログを閉じる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Arch Linux
* Browser: Firefox 128.0.2 (64-bit)
* Server URL: ローカル及び https://mi.miyaco.moe/
* Misskey: 2024.7.0-beta.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

### PR DESCRIPTION
**Pull request by kakkokari-gtyih**
## Why

Fix #14304

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

File: packages/frontend/src/components/MkSystemWebhookEditor.vue [hunk 1]
```diff
@@ -5,14 +5,15 @@ SPDX-License-Identifier: AGPL-3.0-only
...
+	ref="dialogEl"
 	:width="450"
 	:height="590"
 	:canClose="true"
 	:withOkButton="false"
 	:okButtonDisabled="false"
 	@click="onCancelClicked"
 	@close="onCancelClicked"
-	@closed="onCancelClicked"
+	@closed="$emit('closed')"
```
Comment (syuilo) [inline packages/frontend/src/components/MkSystemWebhookEditor.vue]:
```suggestion
	@closed="emit('closed')"
```

Comment (kakkokari-gtyih) [reply packages/frontend/src/components/MkSystemWebhookEditor.vue]: done

**Comment by syuilo** [comment]
🙏🏻
