### PR TITLE
fix(client): hide bot protection warning with disabled registrations

### LINKED ISSUE #8651: Bot protection warning shouldn't be displayed if user registration is deactivated
## 💡 Summary
I think Misskey shouldn't display the Bot protection warning when new user registration is disabled. 
1652387782-grim
1652387821-grim

## 🥰 Expected Behavior
Bot protection warning is not shown if bot configuration is enabled or if new user registration is disabled

## 🤬 Actual Behavior
Bot protection warning is shown, even user registration is disabled.

## 📝 Steps to Reproduce

1. Go to Control Panel
2. Deactivate new User registration
3. Warning about Bot protection (for user registration) is still shown in admin panel

## 📌 Environment

Misskey version: 12.110.1
Your OS: Arch Linux
Your browser: Firefox 100.0

### PR DESCRIPTION
**Pull request by pixeldesu**
# What

Hides the "no bot protection is configured" warning if registrations are disabled

Fixes #8651 

# Why

Disabled registrations do not require a configured captcha, so the warning is just added noise in that case

### CODE REVIEW

File: packages/client/src/pages/admin/index.vue [hunk 1]
```diff
@@ -62,7 +62,7 @@ let view = $ref(null);
 let el = $ref(null);
 let pageProps = $ref({});
 let noMaintainerInformation = isEmpty(instance.maintainerName) || isEmpty(instance.maintainerEmail);
-let noBotProtection = !instance.enableHcaptcha && !instance.enableRecaptcha;
+let noBotProtection = instance.disableRegistration ? false : !instance.enableHcaptcha && !instance.enableRecaptcha;
```
Comment (Johann150) [inline packages/client/src/pages/admin/index.vue]: I think using a ternary expression here is unnecessary. You can use the logical and operator with short circuiting to the same effect:

```suggestion
let noBotProtection = !instance.disableRegistration && !instance.enableHcaptcha && !instance.enableRecaptcha;
```

**Review by Johann150 — APPROVED** [review]

**Review by rinsuki — APPROVED** [review]

**Review by ThatOneCalculator — APPROVED** [review]
