### PR TITLE
enhance: Remote Notes Cleaning timeout bailout logic

### LINKED ISSUE #16592: 「Remote Notes Cleaning」の最低ノート保持日数を変更しても反映されない？
### 💡 Summary

タイトルの通り。
最低ノート保持日数を90日から30日に変更しても反映されていないようである。

この事象を発見した経緯としては、
まず、私が運営しているサーバはRemote Notes Cleaningを有効にして以降、毎日VACUUM FULLを行った後にDBのバックアップを取っているため、毎日のおおまかなDB容量を確認できる。
しばらくは最低ノート保持日数を90日にしていた。数日はDB容量が減っていったのを確認できた。この設定のまま1週間くらいしたら、DB容量が減らなくなった。
容量が減らなくなって数日後、最低ノート保持日数を90日から30日にした。しかしその後少しもDB容量が減らなかったので(普通は減るはず)、最低ノート保持日数の設定が反映されていないのでは？という疑念を抱いている。

### 🥰 Expected Behavior

30日に設定したら30日経過したノートはDBから削除されること。

### 🤬 Actual Behavior

30日経過してもDBから削除されていない。

### 📝 Steps to Reproduce

1. AdminでコントロールパネルのRemote Notes Cleaningをオンにする
2. 最低ノート保持日数を30日に変更する

### 💻 Frontend Environment

```markdown
関係ないと思うが。
* Model and OS of the device(s): Windows 10
* Browser: Chrome 137.0.7151.120
* Server URL: mk.puzzlesskey.com
* Misskey: 2025.9.0
```

### 🛰 Backend Environment (for server admin)

```markdown
Misskeyのバージョン以外関係ない気がするが。
* Installation Method or Hosting Service: 「Ubuntu版Misskeyインストール方法詳説」に近い方法
* Misskey: 2025.9.0
* Node: v22.20.0
* PostgreSQL: psql (PostgreSQL) 18.0 (Ubuntu 18.0-1.pgdg24.04+3)
* Redis: Redis server v=8.2.1
* OS and Architecture: Ubuntu 24.04.3 LTS (GNU/Linux 6.8.0 x86_64)
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

### PR DESCRIPTION
**Pull request by eternal-flame-AD**
## What

Resolves #16592. 

## Why

The original anti-looping logic was too conservative, we should skip instead of bail out if a particular note is too hard to process.

## Additional info (optional)

This is just a sketch, I still need to test this and perhaps lift the logic out so it can be unit tested, don't merge this yet.

## Checklist
- [X] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [X] Update CHANGELOG.md
- [ ] Add tests

### CODE REVIEW

File: packages/backend/src/queue/processors/CleanRemoteNotesProcessorService.ts [hunk 1]
```diff
@@ -155,12 +162,12 @@ export class CleanRemoteNotesProcessorService {
 		// | fff | fff    | TRUE        |
 		// | ggg | ggg    | FALSE       |
 		//
-		const candidateNotesQuery = this.db.createQueryBuilder()
+		const candidateNotesQuery = ({ limit }: { limit: number }) => this.db.createQueryBuilder()
```
Comment (eternal-flame-AD) [inline packages/backend/src/queue/processors/CleanRemoteNotesProcessorService.ts:165]: My bad, I think the primary issue is here. The adaptive limit was not being picked up causing the timeout. 

But it should be much more robust now.

**Comment by eternal-flame-AD** [comment]
I tested the inner query works locally, this setup should also allow a running job to exit cleanly if the user changes the parameters.

**Comment by syuilo** [comment]
🙏
