### PR TITLE
Local only indicator

### LINKED ISSUE #5989: ローカルのみのアイコンがない
## 📝 Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by chocological00**
## Summary
Fix #5989 

Add indicators for local-only and public notes on the right top:
image

(screenshot icon is customized - in the PR the icon is actually :biohazard:, keeping it constant with the compose note modal)

### CODE REVIEW

**Comment by chocological00** [comment]
Hello, any update on this?
FYI, the CI failure is unrelated to this PR and should disappear once merged.

File: src/client/components/note-header.vue [hunk 1]
```diff
@@ -12,7 +12,10 @@
 		<router-link class="created-at" :to="note | notePage">
 			<mk-time :time="note.createdAt"/>
 		</router-link>
-		<span class="visibility" v-if="note.visibility != 'public'">
+		<span class="visibility">
+			<fa v-if="note.localOnly" :icon="faBiohazard"/>
+			<template v-if="note.localOnly">&nbsp;</template>
```
Comment (rinsuki) [inline src/client/components/note-header.vue]: This is a matter of preference, but I think putting <fa> in the <template> would be beautiful because it would have one v-if.

example:

```vue
			<template v-if="note.localOnly">
				<fa :icon="faBiohazard"/>
				&nbsp;
			</template>
```

**Comment by syuilo** [comment]
localOnlyかどうかの情報ってレスポンスに含めるのやめた気がするけどどうだっけ

**Comment by tamaina** [comment]
```bash
$ curl -X POST -k -i 'https://c2.a9z.dev/api/notes/show' --data '{"noteId": "86yiwwyemv"}'
{"id":"86yiwwyemv","createdAt":"2020-05-06T06:27:05.558Z","userId":"81g9ufohhb","user":{"id":"81g9ufohhb","name":null,"username":"aqz","host":null,"avatarUrl":"https://d20bb5quu0uyhd.cloudfront.net/m/thumbnail-77a5c57d-af12-40c8-828b-a212fbdf4f8f.jpg","avatarColor":"rgb(111,118,116)","isAdmin":true,"isCat":true,"emojis":[]},"text":"ろ～かるおんり～","cw":null,"visibility":"public",
"localOnly":true,
"renoteCount":0,"repliesCount":0,"reactions":{},"emojis":[],"fileIds":[],"files":[],"replyId":null,"renoteId":null}
```

まだあるっぽいべ

**Comment by tamaina** [comment]
というかBiohazardいい加減やめませんか？

**Comment by rinsuki** [comment]
それはまた別のissueにすべきでは

**Comment by syuilo** [comment]
publicのアイコン要るかな？

**Comment by chocological00** [comment]
Sorry for late checkup :<

Public icon can be removed from this PR (lmk what you think), although I do think adding it would be nice to make the UX more constant.

Local only indicator *is* needed, as people talking over TL (i.e. the person is reacting to the note, but with a separate note instead of the reply function) have caused some confusion to remote users when a local only note was involved.

**Comment by mei23** [comment]
> publicのアイコン要るかな？

「Public」も「Home」も「Public (local only)」も対等な公開範囲のうちの1つと思ってるので
「Public」も常に表示するものかなと思ってました。
https://github.com/syuilo/misskey/issues/6323#issuecomment-628968783

**Comment by syuilo** [comment]
いったんlocalOnly表示するだけにしよう

**Comment by syuilo** [comment]
👍
