### PR TITLE
Fix: Don't delete remote emoji when import zip

### LINKED ISSUE #15673: Don't delete remote emoji when import zip
### 💡 Summary

When importing emojis using a zip file, remote emojis with the same name are deleted.

絵文字をzipを使って取り込むとき、同じ名前のリモート絵文字が削除されてしまう。

### 🥰 Expected Behavior

Only local emojis of the same name should be replaced.

同名のローカルの絵文字だけを置き換える必要があります。

### 🤬 Actual Behavior

remote emojis with the same name are deleted.

同じ名前のリモート絵文字が削除されてしまう。

### 📝 Steps to Reproduce

1. export emoji in zip format
2. import emoji with zip

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: docker compose
* Misskey:2025.3.1
* Node: 22
* PostgreSQL: postgres:16-bookworm + pgroonga
* Redis: redis:7-alpine
* OS and Architecture: Ubuntu 24.04, aarch64
```

### Do you want to address this bug yourself?

- [x] Yes, I will patch the bug myself and send a pull request

### PR DESCRIPTION
**Pull request by yunochi**
## What

fix emoji zip import (https://github.com/misskey-dev/misskey/issues/15673)

## Why

- https://github.com/misskey-dev/misskey/issues/15673

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Review by KisaragiEffective — APPROVED** [review]

File: packages/backend/src/queue/processors/ImportCustomEmojisProcessorService.ts [hunk 1]
```diff
@@ -85,7 +86,8 @@ export class ImportCustomEmojisProcessorService {
 				}
 				const emojiPath = outputPath + '/' + record.fileName;
 				await this.emojisRepository.delete({
-					name: emojiInfo.name,
+					name: emojiInfo.name,
```
Comment (zyoshoka) [inline packages/backend/src/queue/processors/ImportCustomEmojisProcessorService.ts]:
```suggestion
					name: emojiInfo.name,
```
