### PR TITLE
fix missing strings

### LINKED ISSUE #7411: Missing strings (English)
## 💡 Summary

Some strings miss in English language.

1. Instance - Settings - Basic Info
2. Instance - Settings - Proxy Account
3. Instance - Federation - Sort
4. Instance - Reports - State

Screenshots

1. 
2. 
3. 
4. 

## 🙂 Expected Behavior

See text

## ☹️ Actual Behavior

No text

## 📝 Steps to Reproduce

1. Set English language
2. Open Instance - Settings - Basic Info
3. Open Instance - Settings - Proxy Account
4. Open Instance - Federation - Sort
5. Open Instance - Reports - State

## 📌 Environment

Misskey - v12.75.1
Node.js - v14.16.0
PostgreSQL - v13.2 (Debian 13.2-1.pgdg100+1)
Redis - v5.0.3

### PR DESCRIPTION
**Pull request by Johann150**
Fix #7411

# What
The translations in the federation sorting menu have been fixed.

# Why
The sorting menu contained multiple entries that said only ` (Descending)` or ` (Ascending)` because translations were missing or the wrong translation key was used.

# screenshot
<details>
<summary>screenshot old</summary>

</details>
<details>
<summary>screenshot new</summary>

</details>

### CODE REVIEW

**Comment by Johann150** [comment]
すみません、日本語が下手です。もし、新しい日本語のフレーズに間違いがあれば、修正してください。

File: src/client/pages/federation.vue [hunk 1]
```diff
@@ -28,14 +28,14 @@
...
 				<option value="+followers">{{ $ts.followers }} ({{ $ts.descendingOrder }})</option>
 				<option value="-followers">{{ $ts.followers }} ({{ $ts.ascendingOrder }})</option>
-				<option value="+caughtAt">{{ $ts.caughtAt }} ({{ $ts.descendingOrder }})</option>
-				<option value="-caughtAt">{{ $ts.caughtAt }} ({{ $ts.ascendingOrder }})</option>
-				<option value="+lastCommunicatedAt">{{ $ts.lastCommunicatedAt }} ({{ $ts.descendingOrder }})</option>
-				<option value="-lastCommunicatedAt">{{ $ts.lastCommunicatedAt }} ({{ $ts.ascendingOrder }})</option>
+				<option value="+caughtAt">{{ $ts.registeredAt }} ({{ $ts.descendingOrder }})</option>
+				<option value="-caughtAt">{{ $ts.registeredAt }} ({{ $ts.ascendingOrder }})</option>
+				<option value="+lastCommunicatedAt">{{ $ts.lastRequest }} ({{ $ts.descendingOrder }})</option>
+				<option value="-lastCommunicatedAt">{{ $ts.lastRequest }} ({{ $ts.ascendingOrder }})</option>
```
Comment (syuilo) [inline src/client/pages/federation.vue]: lastCommunicatedAtは「直近のリクエスト送信」だけではなく「直近のリクエスト受信」も含まれた時間なので、「直近の通信」がいいと思います。

Since lastCommunicatedAt is the time that includes not only "last request sent" but also "last request received", I think "直近の通信"(last communication) is better.

Comment (Johann150) [reply src/client/pages/federation.vue]: 👍  I changed it

**Comment by Johann150** [comment]
fixes #7411

File: src/client/pages/federation.vue (hunk 1 above)
Comment (robflop) [reply src/client/pages/federation.vue]: You've not changed the name of the localization string yet, might also want to do that.

**Comment by syuilo** [comment]
🙏
